### ISSUE TITLE
Enhance energy statistics for solarbank 2 and smartreader

### ISSUE THREAD

**Issue by thomluther** [thomluther/anker-solix-api#101]
The energy statistics endpoint on the server has been enhanced with totals solarbank 2 and smartreader devices.
Additionally 2 more regular statistic types have been added for 'home_usage' and 'grid' energy.
This additional types should be optionally supported in the daily energy statistics helper methods as well as the energy_export utility.

**Comment by thomluther** [comment]
Note: Any solarbank 2 and smartmeter enhancements needs to be tested by the community!

**Comment by kitokirisaki** [comment]
@thomluther if you want me to check / test something, just ping me. I don't have the smart meter right now installed but should happen hopefully also soon.

**Comment by Disane87** [comment]
If you need some tests, you can ping me too. Got my SolarBank 2 pro today and the smart meter is coming tomorrow. Will be open for assistance :)

**Comment by thomluther** [comment]
Added new metrics to export, but will need example exports to understand how they can be used exactely for the energy details and HA integration
