### ISSUE TITLE
Add support for smartmeter device

### ISSUE THREAD

**Issue by thomluther** [thomluther/anker-solix-api#106]
This is a new device, but it must be validated how the API structure look like for the smartmeter .
Is it included in the scene info response for the site?
Does it need separate endpoints to get the values?

System export examples are needed with smartmeter devices included in the power system.

**Comment by thomluther** [comment]
possible Interpretation:
```
"grid_info": {
"grid_list": [
{
"device_pn": "pn",
"device_sn": "SN",
"device_name": "Smart Meter",
"device_img": "",
"create_time": 1718626744,
"status": "1", => same cloud connection coding as for other devices (0/1)
"bind_site_status": "",
"wireless_type": "" => Missing, typically indicates the connected network type in relation to wifi list response
}
],
"photovoltaic_to_grid_power": "0", => grid export in W
"grid_to_home_power": "669", => grid import in W
"grid_status": 0, => translation table needed
"has_history_data": true => App indicator field to display extra tab for grid statistics?
},
```

A translation table for the grid_status is needed with possible codes seen and their actual meaning to the smart meter or grid, e.g. outage, connection loss, AI mode activation etc.

**Comment by thomluther** [comment]
@thealkly do you have capability to test various conditions with the Smartmeter to verify grid_status code changes in the solarbank Monitor? You could watch the App with the main account meanwhile to see and compare messages with the Status code.
Following tests might change the status:
- Remove a clamp (may not change anything, will just measure power to 0W on this phase?
- Reverse a clamp (may not change anything, will just measure power incorrectly?
- Remove the clamps connection cable /all clamps disconnected
- if you have the smartreader phases after a circuit breaker:
  - break one phase
  - break all phases => This should switch off the smartreader too, so no longer reporting to the cloud?

**Comment by nicolinuxfr** [comment]
> Reverse a clamp (may not change anything, will just measure power incorrectly?

Since I did install the clamp the wrong way at first, I can confirm it will measure the power incorrectly. So negative values when you are using power from the grid and positive if you are sending electricity.

My installation needs only one clamp, but nothing about that is visible inside the app, so we must use the API to check that point.

**Comment by nschllr** [comment]
Hi, as far as I can see from the manual, the communication between the smart meter and the Solix 2 is done without cloud access, using either Bluetooth or Wi-Fi (LAN, no internet needed). This explains why it is able to react so fast to changes in the current energy consumption. If so, it would be awesome if someone could capture the traffic between the Solix 2 and the smart meter (I do not own a smartmeter). Maybe those packets are not encrypted, or at least we might find the endpoint with which we can communicate without cloud access (this might also be a nice workaround for the 0W responses). 

However, there's a chance that the LAN interface is only available if a smart meter is connected.

**Comment by nicolinuxfr** [comment]
> using either Bluetooth or Wi-Fi

The Smart Meter 2 is connected through Wi-Fi only. And I think you're right, it's a direct LAN connection between the two.

**Comment by stephan-l** [comment]
I just gave it another try and scanned Solarbank and Smartmeter for open ports. All closed. So no possibility for a direct TCP connection.
Furthermore I captured all traffic from both. But there is only a connection to ec2-3-78-2-21.eu-central-1.compute.amazonaws.com.8883
So I see only a cloud based MQTT-connection. There could be a BT connection but that doesn't make sense if both devices are separated further.

**Comment by thealkly** [comment]
> @thealkly do you have capability to test various conditions with the Smartmeter to verify grid_status code changes in the solarbank Monitor? You could watch the App with the main account meanwhile to see and compare messages with the Status code. Following tests might change the status:
> 
> * Remove a clamp (may not change anything, will just measure power to 0W on this phase?
> * Reverse a clamp (may not change anything, will just measure power incorrectly?
> * Remove the clamps connection cable /all clamps disconnected
> * if you have the smartreader phases after a circuit breaker:
>   
>   * break one phase
>   * break all phases => This should switch off the smartreader too, so no longer reporting to the cloud?

* I only have one phase. Perhaps someone else can test this. But it seems to add all phases as I did not change any setting.
* I did also a wrong installation first. Back than I had a different beta app. But the behavior is as described by @nicolinuxfr it will assume I exported the power instead of import.
* if I disconnect:
```
    "retain_load": "200W",
    "scene_mode": 1,
    "home_load_power": "324",
    "updated_time": "01-01-0001 00:00:00",
    "power_site_type": 5,
    "site_id": "9b8e5636-f604-4249-844c-44c11cc110ad",
    "powerpanel_list": [],
    "grid_info": {
      "grid_list": [
        {
          "device_pn": "123",
          "device_sn": "123",
          "device_name": "Smart Meter",
          "device_img": "",
          "create_time": 123,
          "status": "1",
          "bind_site_status": "",
          "wireless_type": ""
        }
      ],
      "photovoltaic_to_grid_power": "0",
      "grid_to_home_power": "324",
      "grid_status": 0,
      "has_history_data": true
```
offline:

```
"grid_info": {
      "grid_list": [
        {
          "device_pn": "123",
          "device_sn": "123",
          "device_name": "Smart Meter",
          "device_img": "",
          "create_time": 123,
          "status": "1",
          "bind_site_status": "",
          "wireless_type": ""
        }
      ],
      "photovoltaic_to_grid_power": "0",
      "grid_to_home_power": "0",
      "grid_status": 0,
      "has_history_data": true
    },
```
I think Grid Status is still 0 because the smart meter is connected and assuming grid is available. 

I'm not sure if bluetooth is an option. My electrical installation is quite fare away, with many walls in-between. 
I could try in the next days to disable the internet for a couple of minutes and check if 0 grid is still working.
If it is still working, there is probably some local connection. Perhaps some local MQTT?

**Comment by thomluther** [comment]
Yeah, maybe the grid_status is just changed when there is power loss on 1-2 phases, because on total grid loss the smartmeter is down too and cannot report anything.
So will keep this 0 reported as OK and if it will every report anything different in future it will have to be added via an issue.
I think for the smart meter we are good then, unless someone finds anything missing or wrong for it in the solarbank monitor.

The smart meter is not listed in the auto-update devices. Is not not supported either in the App for auto-update settings?

**Comment by nicolinuxfr** [comment]
> The smart meter is not listed in the auto-update devices. Is not not supported either in the App for auto-update settings?

Indeed, only the main Solarbank 2 unit. Even the battery extension seems not to be auto-updatable. 
![IMG_2733](https://github.com/user-attachments/assets/0b979aff-ade9-457c-9bc8-ff2e26d08edc)

**Comment by Lenoirio** [comment]
This YouTuber got a bunch of questions answered (by Anker themself). 

https://www.youtube.com/watch?v=X4WQUk2X8lM&t=53s   (it's in German but maybe auto-subtitles work)

The first one is interessting: Is the communication between the SolarBank and the SmartMeter still possible if no internet is available: Answer from Anker is *YES*  within the same LAN (he even explains a certain option you need to enable for the very popular FritzBox (in Germany at least))
