### ISSUE TITLE
Hoymiles HMS-xxxx-4T

### ISSUE THREAD

**Issue by SchaichaD** [thomluther/anker-solix-api#134]
Hello,
is it possible to get the values also from port 3 and port 4?
kind regards
Detlef

**Comment by thomluther** [comment]
Hi @SchaichaD 
This is the Anker Solix Api repo. This does not get any values from Hoymiles inverters....
You will have to look for integrations support the hoxmiles models. If they have no Wifi included, you will also need a DTU to get Hoymiles values (OpenDTU or Ahoy DTU)
