### ISSUE TITLE
Missing Attribute for Anker Solix 2 Pro: Temperature

### ISSUE THREAD

**Issue by kantmn** [thomluther/anker-solix-api#159]
Hi there,

i am wondering why the temperature of the solix 2 pro is not accessible via this api.
checked also the export and so far i did not find the related key/value pair for this.

using the anker app, you can see the device temp when opening the solix device page, so i guess this is also provided from anker somehow.
![image](https://github.com/user-attachments/assets/56ef4673-192f-46d1-9449-38e7f2a5f296)

did i miss the key/value or is it not available so far?

thanks and best regards
kantm

**Comment by thomluther** [comment]
Its not available via cloud API. It seems to be available only via BT or Mqtt Api, which is used for remote device management.
You can try to explore New device_attr endpoints in issue #107 if they respond anything when you use correct parameters or attribute names, which are unknown...
