### ISSUE TITLE
Feat: Use a packagemanger to manage dependencies

### ISSUE THREAD

**Issue by stuertz** [thomluther/anker-solix-api#32]
Currently the documentation states what are the direct deps. If not using `pyenv` collisions of versions are very possible.

To use isolated envs there are tools like pipenv (https://pipenv.pypa.io/en/latest/) or more modern ones like poetry (https://pypi.org/project/poetry/).

If accepted and decision for one of these tools I would be happy to add this

**Comment by thomluther** [comment]
Hi @stuertz , yes please make the necessary changes and I'm happy to commit.
I don't care which tool to use, since I have no experience with any of them.
